[tool.poetry]
name = "assinatura-digital-clicksign"
version = "0.1.0"
description = ""
authors = ["Rodrigo Alves Tenório <rodten23@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.*"
requests = "^2.32.3"
flask = "^3.1.0"
httpx = {extras = ["http2"], version = "^0.28.1"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
